# Generated by Django 5.1.1 on 2024-10-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_total_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_time',
        ),
    ]
